import Head from "next/head";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import { sanityClient, urlFor } from "../sanity";
import { Post } from "../typings";
import Link from "next/link.js";
import Image from "next/image";

// server side rendering the page and quering data from sanity cms
export const getServerSideProps = async () => {
  const query = `*[_type == "post"]{
    _id,
    title,
    author -> {
      name,
      image
    },
    description,
    mainImage,
    slug
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};

export default function Home({ posts }: { posts: Post }) {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>sBlogger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main>{/* Posts */}</main>
      {/* have to wrap the posts in fragment otherwise we'll get type error */}
      <div>
        <>
          {posts.map((post) => (
            <Link key={post._id} href={`/post/${post.slug.current}`}>
              <Image
                height={300}
                width={300}
                src={urlFor(post.mainImage).url()!}
                alt={`${post.title} image`}
              />
            </Link>
          ))}
        </>
      </div>
    </div>
  );
}
